### ISSUE TITLE
No encuentro la plantilla "TikTok Events Api (Official)" en la galeria de google tag manager

### ISSUE THREAD

**Issue by digitubes** [tiktok/gtm-template-eapi#1]
Hola Esta plantilla no esta en la galeria de google tag manager. Como puedo incluirla?

**Comment by hanzhangtt** [comment]
Hello, our google tag manager template was recently included in Google Community Gallery. Please see the link [here](https://tagmanager.google.com/gallery/#/owners/tiktok/templates/gtm-template-eapi) 

For more development docs, please read our [doc](https://ads.tiktok.com/marketing_api/docs?id=1772372080226305). Thank you ~
