### ISSUE TITLE
Add support of Server logging standard

### ISSUE THREAD

**Issue by Bukashk0zzz** [tiktok/gtm-template-eapi#3]
Hi,

What do you think about adding standardized logs to this tag?
Currently, all popular tags support this standard which allows debugging more easier.
If this is ok for you we can prepare PR for you.

https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-3.md

**Comment by yangqi-tiktok** [comment]
@Bukashk0zzz Thanks for the feedback. 
Yes this is something we'd like to support, and feel free to send over the PR.

**Comment by tt-hubenlin** [comment]
@Bukashk0zzz @kHorozhanov Thank you for sending over PR to us.
