### ISSUE TITLE
Hola Esta plantilla no esta en la galeria de google tag manager. Como puedo incluirla?

### ISSUE THREAD

**Issue by zerovee** [tiktok/gtm-template-eapi#6]
Hola Esta plantilla no esta en la galeria de google tag manager. Como puedo incluirla?

**Comment by fvayas** [comment]
Talvez pudiste resolverlo?

**Comment by ThoMei** [comment]
The GTM TikTok EAPI template is only accessible through a Server container. You are likely checking/looking for the template in a web container and it will not appear in that gallery.
